// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List active Alpenzo products, optionally filtered by category (e.g. tshirt, sweatshirt, hoodie).",
  inputSchema: {
    category: z.string().optional().describe("Optional category slug to filter by."),
    limit: z.number().int().optional().describe("Max rows to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("products").select("id,name,description,price,image_url,category,stock").eq("is_active", true);
    if (category) q = q.eq("category", category);
    q = q.limit(Math.min(Math.max(limit ?? 50, 1), 200));
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single Alpenzo product by its id (uuid).",
  inputSchema: {
    id: z2.string().describe("Product id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("products").select("id,name,description,price,image_url,category,stock,is_active").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { product: data } };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List the distinct product category slugs available in the Alpenzo catalog.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("products").select("category").eq("is_active", true);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const categories = Array.from(new Set((data ?? []).map((r) => r.category).filter(Boolean)));
    return {
      content: [{ type: "text", text: JSON.stringify(categories) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/list-cart.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_cart_default = defineTool4({
  name: "list_cart",
  title: "List cart items",
  description: "List the signed-in user's cart items.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("cart_items").select("id,product_id,quantity,created_at,updated_at").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { items: data ?? [] } };
  }
});

// src/lib/mcp/tools/add-to-cart.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var add_to_cart_default = defineTool5({
  name: "add_to_cart",
  title: "Add to cart",
  description: "Add a product to the signed-in user's cart.",
  inputSchema: {
    product_id: z3.string().describe("Product id (uuid) to add."),
    quantity: z3.number().int().optional().describe("Quantity to add. Defaults to 1.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ product_id, quantity }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const qty = Math.max(1, Math.min(quantity ?? 1, 999));
    const { data, error } = await supabaseForUser(ctx).from("cart_items").insert({ user_id: ctx.getUserId(), product_id, quantity: qty }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { item: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "afaiczufrblvyrscyssj";
var mcp_default = defineMcp({
  name: "alpenzo-mcp",
  title: "Alpenzo",
  version: "0.1.0",
  instructions: "Tools for the Alpenzo apparel shop. Browse the product catalog with list_products/get_product/list_categories, and manage the signed-in user's cart with list_cart and add_to_cart.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, list_categories_default, list_cart_default, add_to_cart_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
